name: CI

on:
  push:
    branches: [ master ]
    # Only run if a .go file, mod files, the Dockerfile, or any file in /static has been changed.
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - 'static/**'

jobs:
  build:
    name: Build & Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # This action will fail if any part of the Dockerfile fails.
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: psidex/portsmouthshippingmovements
          tags: latest